### ISSUE TITLE
shift-spec-idl?

### ISSUE THREAD

**Issue by tolmasky** [shapesecurity/shift-spec-js#1]
I'm trying to fix shift-traverse which is pretty out of date I guess from the latest shift stuff, so I came here to try to see what the latest spec is, but this code seems to reference ../shift-spec-idl which from what I see of the repos isn't around?

**Comment by tolmasky** [comment]
Ah, found it.

**Comment by michaelficarra** [comment]
Yes, @Constellation has not yet updated shift-traverse with ES6 support. I've opened https://github.com/Constellation/shift-traverse-js/issues/3.

**Comment by michaelficarra** [comment]
For others' reference, the `shift-spec-idl` npm package is a distribution of the `spec.idl` file in [the Shift AST specification](https://github.com/shapesecurity/shift-spec). The `shift-spec` package is the JavaScript representation of that file (this repo).
